[build]
  functions = "functions"
  environment = { MONGODB_URI = "", DB_NAME = "unit", COLLECTION_CITY = "city", COLLECTION_DISTRICT = "district", COLLECTION_WARD = "ward"}

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from="/*"
  to="/.netlify/functions/:splat"
  status=200
